apiVersion: apps/v1
kind: Deployment
metadata:
  name: contract-observer-service
spec:
  selector:
    matchLabels:
      app: contract-observer-service
  template:
    metadata:
      labels:
        app: contract-observer-service
    spec:
      containers:
        - name: contract-observer-service
          image: techxtt/contract-observer-service-image:latest
          envFrom:
            - configMapRef:
                name: contract-observer-service-env-config
            - secretRef:
                name: contract-observer-service-env-secrets
          resources:
            limits:
              memory: "512Mi"
              cpu: "1"
            requests:
              memory: "512Mi"
              cpu: "1"
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: listings-service
spec:
  selector:
    matchLabels:
      app: listings-service
  template:
    metadata:
      labels:
        app: listings-service
    spec:
      containers:
        - name: listings-service
          image: techxtt/listings-service-image:latest
          envFrom:
            - configMapRef:
                name: listings-service-env-config
            - secretRef:
                name: listings-service-env-secrets
          resources:
            limits:
              memory: "512Mi"
              cpu: "1"
            requests:
              memory: "512Mi"
              cpu: "1"
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: tokenization-service
spec:
  selector:
    matchLabels:
      app: tokenization-service
  template:
    metadata:
      labels:
        app: tokenization-service
    spec:
      containers:
        - name: tokenization-service
          image: techxtt/tokenization-service-image:latest
          envFrom:
            - configMapRef:
                name: tokenization-service-env-config
            - secretRef:
                name: db-env-secrets
          resources:
            limits:
              memory: "512Mi"
              cpu: "1"
            requests:
              memory: "512Mi"
              cpu: "1"
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: api-gateway-service
spec:
  selector:
    matchLabels:
      app: api-gateway-service
  template:
    metadata:
      labels:
        app: api-gateway-service
    spec:
      containers:
        - name: api-gateway-service
          image: techxtt/api-gateway-service-image:latest
          envFrom:
            - configMapRef:
                name: api-gateway-service-env-config
          resources:
            limits:
              memory: "512Mi"
              cpu: "1"
            requests:
              memory: "512Mi"
              cpu: "1"
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: order-service
spec:
  selector:
    matchLabels:
      app: order-service
  template:
    metadata:
      labels:
        app: order-service
    spec:
      containers:
        - name: order-service
          image: techxtt/order-service-image:latest
          envFrom:
            - configMapRef:
                name: order-service-env-config
            - secretRef:
                name: db-env-secrets
          resources:
            limits:
              memory: "512Mi"
              cpu: "1"
            requests:
              memory: "512Mi"
              cpu: "1"
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: auth-service
spec:
  selector:
    matchLabels:
      app: auth-service
  template:
    metadata:
      labels:
        app: auth-service
    spec:
      containers:
        - name: auth-service
          image: techxtt/auth-service-image:latest
          envFrom:
            - configMapRef:
                name: auth-service-env-config
            - secretRef:
                name: auth-service-env-secrets
          resources:
            limits:
              memory: "512Mi"
              cpu: "1"
            requests:
              memory: "512Mi"
              cpu: "1"
---
apiVersion: v1
kind: Service
metadata:
  name: contract-observer-service
spec:
  selector:
    app: contract-observer-service
  ports:
    - protocol: TCP
      port: 50055
      targetPort: 50055
---
apiVersion: v1
kind: Service
metadata:
  name: listings-service
spec:
  selector:
    app: listings-service
  ports:
    - protocol: TCP
      port: 50053
      targetPort: 50053
---
apiVersion: v1
kind: Service
metadata:
  name: tokenization-service
spec:
  selector:
    app: tokenization-service
  ports:
    - protocol: TCP
      port: 50056
      targetPort: 50056
---
apiVersion: v1
kind: Service
metadata:
  name: orders-service
spec:
  selector:
    app: orders-service
  ports:
    - protocol: TCP
      port: 50054
      targetPort: 50054
---
apiVersion: v1
kind: Service
metadata:
  name: auth-service
spec:
  selector:
    app: auth-service
  ports:
    - protocol: TCP
      port: 50052
      targetPort: 50052
---
apiVersion: v1
kind: Service
metadata:
  name: api-gateway-service
spec:
  selector:
    app: api-gateway-service
  ports:
    - protocol: TCP
      port: 50051
      targetPort: 50051
