apiVersion: apps/v1
kind: Deployment
metadata:
  name: contract-observer-service
spec:
  selector:
    matchLabels:
      app: contract-observer-service
  template:
    metadata:
      labels:
        app: contract-observer-service
    spec:
      containers:
        - name: contract-observer-service
          image: contract-observer-service-image
          envFrom:
            - configMapRef:
                name: contract-observer-service-env-config
            - secretRef:
                name: contract-observer-service-env-secrets
          resources:
            limits:
              memory: "512Mi"
              cpu: "1"
            requests:
              memory: "512Mi"
              cpu: "1"
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: listings-service
spec:
  selector:
    matchLabels:
      app: listings-service
  template:
    metadata:
      labels:
        app: listings-service
    spec:
      containers:
        - name: listings-service
          image: listings-service-image
          envFrom:
            - configMapRef:
                name: listings-service-env-config
            - secretRef:
                name: listings-service-env-secrets
          resources:
            limits:
              memory: "512Mi"
              cpu: "1"
            requests:
              memory: "512Mi"
              cpu: "1"
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: tokenization-service
spec:
  selector:
    matchLabels:
      app: tokenization-service
  template:
    metadata:
      labels:
        app: tokenization-service
    spec:
      containers:
        - name: tokenization-service
          image: tokenization-service-image
          envFrom:
            - configMapRef:
                name: tokenization-service-env-config
            - secretRef:
                name: tokenization-service-env-secrets
          resources:
            limits:
              memory: "512Mi"
              cpu: "1"
            requests:
              memory: "512Mi"
              cpu: "1"