apiVersion: v1
kind: Secret
metadata:
  name: tokenization-service-env-secrets
type: Opaque
data:
  PINATA_API_KEY: ""
  PINATA_SECRET_API_KEY: ""
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: tokenization-service-env-config
data:
  PORT: "50056"
---
apiVersion: v1
kind: Secret
metadata:
  name: db-env-secrets
type: Opaque
data:
  DB_HOST: ""
  DB_PORT: ""
  DB_USER: ""
  DB_PASSWORD: ""
  DB_NAME: ""
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: listings-service-env-config
data:
  TCP_PORT: "50053"
  TOKENIZATION_SERVICE_ADDRESS: "localhost:50056"
---
apiVersion: v1
kind: Secret
metadata:
  name: contract-observer-service-env-secrets
type: Opaque
data:
  WS_URL: ""
  CONTRACT_ADDRESS: ""
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: contract-observer-service-env-config
data:
  LISTINGS_SERVICE_CLIENT: "localhost:50053"
  ORDERS_SERVICE_CLIENT: "localhost:50054"
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: api-gateway-service-env-config
data:
  PORT: "localhost:50053"
  LISTINGS_SERVICE_ADDRESS: "localhost:50053"
  ORDERS_SERVICE_ADDRESS: "localhost:50054"
  AUTH_SERVICE_ADDRESS: "localhost:50052"
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: orders-env-config
data:
  TCP_PORT: "localhost:50054"
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: auth-env-config
data:
  TCP_PORT: "localhost:50052"
  JWT_EXPIRATION_HOURS: "24"
---
apiVersion: v1
kind: Secret
metadata:
  name: auth-service-env-secrets
type: Opaque
data:
  DB_HOST: ""
  DB_PORT: ""
  DB_USER: ""
  DB_PASSWORD: ""
  DB_NAME: ""
  JWT_SECRET_KEY: ""
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: postgres-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: postgres
  template:
    metadata:
      labels:
        app: postgres
    spec:
      containers:
      - name: postgres
        image: postgres:latest
        ports:
        - containerPort: 50050
---
apiVersion: v1
kind: Service
metadata:
  name: postgres-service
spec:
  selector:
    app: postgres
  ports:
    - protocol: TCP
      port: 50050
      targetPort: 50050