apiVersion: v1
kind: Service
metadata:
  name: service-deployment
  namespace: namespace-workflow-1710426857024
spec:
  type: LoadBalancer
  selector:
    app: service-deployment
  ports:
    - protocol: TCP
      port: 50051
      targetPort: 50051